# Generated by Django 4.0.4 on 2022-06-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentsmodel',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='studentsmodel',
            name='roll_no',
            field=models.IntegerField(unique=True),
        ),
    ]
