# Generated by Django 3.0.6 on 2020-05-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('genre', models.CharField(max_length=256)),
                ('singer', models.CharField(max_length=256)),
                ('mp3', models.FileField(upload_to='media/mp3')),
            ],
        ),
    ]
