# Generated by Django 3.0.7 on 2020-08-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('genre', models.CharField(max_length=256)),
                ('singer', models.CharField(max_length=256)),
                ('mp3', models.FileField(upload_to='media%H%M%S')),
            ],
            options={
                'verbose_name_plural': 'My PlayList',
            },
        ),
    ]
